# Generated by Django 3.0.2 on 2020-01-03 09:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
